<?php

use app\models\base\ProductVariant;
use app\models\base\Produk;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\ProductDetail $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin(
            [
                'id' => 'ProductDetail',
                'layout' => 'horizontal',
                'enableClientValidation' => true,
                'errorSummaryCssClass' => 'error-summary alert alert-error'
            ]
        );
        ?>

        <?= $form->field($model, 'id')->textInput() ?>
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'id_product')->dropDownList(
            \yii\helpers\ArrayHelper::map(app\models\Produk::find()->all(), 'id', 'id'),
            [
                'prompt' => 'Select',
                'disabled' => (isset($relAttributes) && isset($relAttributes['id_product'])),
            ]
        ); ?>
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'color')->dropDownList(
            \yii\helpers\ArrayHelper::map(app\models\ProductVariant::find()->where([
                'type' => 'color',
                'id_product' => 1
            ])->all(), 'id', 'value'),
            [
                'prompt' => 'Select',
                'disabled' => (isset($relAttributes) && isset($relAttributes['id_variant'])),
            ]
        ); ?>
        <?= $form->field($model, 'color')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'size')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'stok')->textInput() ?>
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'id_variant')->dropDownList(
            \yii\helpers\ArrayHelper::map(app\models\ProductVariant::find()->all(), 'id', 'id'),
            [
                'prompt' => 'Select',
                'disabled' => (isset($relAttributes) && isset($relAttributes['id_variant'])),
            ]
        ); ?>



        <?= $form->field($model, 'id_product')->dropDownList(
            \yii\helpers\ArrayHelper::map(app\models\Produk::find()->all(), 'id', 'id'),
            [
                'prompt' => 'Select Product',
                'onchange' => '
                $.post("index.php?r=color/lists&id=' . '"+$(this).val(),function(data)
                { $("select#productdetail-color" ).html(data);
            });'
            ]
        ); ?>

        <?= $form->field($model, 'color')->dropDownList(
            \yii\helpers\ArrayHelper::map(app\models\ProductVariant::find()->all(), 'id', 'value'),
            [
                'prompt' => 'Select color',
            ]
        ) ?>


        <hr />
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>