<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\controllers\base;

use app\models\KategoriProduk;
use Yii;


use app\components\UploadFile;
use app\models\search\KategoriProdukSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
use app\models\Action;
use yii\web\UploadedFile;

/**
 * KategoriProdukController implements the CRUD actions for KategoriProduk model.
 */
class KategoriProdukController extends Controller
{
    use UploadFile;

    /**
     * @var boolean whether to enable CSRF validation for the actions in this controller.
     * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
     */
    public $enableCsrfValidation = false;
    public function behaviors()
    {
        //NodeLogger::sendLog(Action::getAccess($this->id));
        //apply role_action table for privilege (doesn't apply to super admin)
        return Action::getAccess($this->id);
    }

    /**
     * Lists all KategoriProduk models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new KategoriProdukSearch;
        $dataProvider = $searchModel->search($_GET);

        Tabs::clearLocalStorage();

        Url::remember();
        \Yii::$app->session['__crudReturnUrl'] = null;

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single KategoriProduk model.
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id)
    {
        \Yii::$app->session['__crudReturnUrl'] = Url::previous();
        Url::remember();
        Tabs::rememberActiveState();

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new KategoriProduk model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new KategoriProduk;


        try {
            if ($model->load($_POST)) {
                $icon2 = UploadedFile::getInstance($model, 'icon2');
                $response = $this->uploadFile($icon2, 'icon2');
                if ($response->success == false) {
                    Yii::$app->session->setFlash('danger', 'Gagal Upload Foto');
                    // goto end;
                    return $this->render('create', ['model' => $model]);
                }
                $model->gambar = $response->filename;
                if ($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing KategoriProduk model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $oldicon2 = $model->icon2;

        if ($model->load($_POST)) {
            $icon2 = UploadedFile::getInstance($model, 'icon2');
            if ($icon2 != NULL) {
                # store the source file name
                // $model->gambar = $gambar->name;
                // $arr = explode(".", $gambar->name);
                // $extension = end($arr);

                // # generate a unique file name
                // $model->gambar = Yii::$app->security->generateRandomString() . ".{$extension}";

                // # the path to save file
                // if (file_exists(Yii::getAlias("@app/web/uploads/testimonials/")) == false) {
                //     mkdir(Yii::getAlias("@app/web/uploads/testimonials/"), 0777, true);
                // }
                // $path = Yii::getAlias("@app/web/uploads/testimonials/") . $model->gambar;
                $response = $this->uploadFile($icon2, 'icon2');
                if ($response->success == false) {
                    Yii::$app->session->setFlash('danger', 'Gagal Upload Foto');
                    // goto end;
                    return $this->render('create', ['model' => $model]);
                }
                $model->icon2 = $response->filename;
                if ($oldicon2 != NULL) {

                    // $gambar->saveAs($path);
                    // unlink(Yii::$app->basePath . '/web/uploads/testimonials/' . $oldgambar);
                }
            } else {
                $model->icon2 = $oldicon2;
            }

            $model->save();
            return $this->redirect(Url::previous());
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }



        if ($model->load($_POST) && $model->save()) {
            return $this->redirect(Url::previous());
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing KategoriProduk model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            \Yii::$app->getSession()->addFlash('error', $msg);
            return $this->redirect(Url::previous());
        }

        // TODO: improve detection
        $isPivot = strstr('$id', ',');
        if ($isPivot == true) {
            return $this->redirect(Url::previous());
        } elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
            Url::remember(null);
            $url = \Yii::$app->session['__crudReturnUrl'];
            \Yii::$app->session['__crudReturnUrl'] = null;

            return $this->redirect($url);
        } else {
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the KategoriProduk model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return KategoriProduk the loaded model
     * @throws HttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = KategoriProduk::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}
