<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\DetailPesanan $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin(
            [
                'id' => 'DetailPesanan',
                'layout' => 'horizontal',
                'enableClientValidation' => true,
                'errorSummaryCssClass' => 'error-summary alert alert-error'
            ]
        );
        ?>

        <?= $form->field($model, 'id')->textInput() ?>
        <?= $form->field($model, 'invoice')->textInput() ?>
        <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'nominal')->textInput() ?>
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'usrid')->dropDownList(
            \yii\helpers\ArrayHelper::map(app\models\User::find()->all(), 'id', 'name'),
            [
                'prompt' => 'Select',
                'disabled' => (isset($relAttributes) && isset($relAttributes['usrid'])),
            ]
        ); ?>
        <?= $form->field($model, 'alamat_pembeli')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'alamat_penjual')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'berat')->textInput() ?>
        <?= $form->field($model, 'ongkir')->textInput() ?>
        <?= $form->field($model, 'kurir')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'paket')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'dari')->textInput() ?>
        <?= $form->field($model, 'tujuan')->textInput() ?>
        <?= $form->field($model, 'resi')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'kirim')->textInput() ?>
        <?= $form->field($model, 'id_bayar')->textInput() ?>
        <?= $form->field($model, 'ajukanbatal')->textInput() ?>
        <?= $form->field($model, 'keterangan')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'created_at')->textInput() ?>
        <?= $form->field($model, 'updated_at')->textInput() ?>
        <?= $form->field($model, 'status_id')->textInput() ?>
        <hr />
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>