<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\PesananSearch $searchModel
 */

$this->title = 'DetailPesanan';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
</p>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="box box-info">
    <div class="box-body">
        <?php
        $tabs = [
            'belum-bayar' => 'Belum Bayar',
            'perlu-dikirim' => 'Perlu Dikirim',
            'sedang-dikirim' => 'Sedang Dikirim',
            'selesai' => 'Selesai',
            'dibatalkan' => 'Dibatalkan',
        ];
        $activeTab = Yii::$app->request->get('tab', 'belum-bayar');
        ?>

        <ul class="nav nav-tabs">
            <?php foreach ($tabs as $tab => $label) : ?>
                <li<?= $activeTab === $tab ? ' class="active"' : '' ?>>
                    <?= Html::a($label, ['pesanan/index', 'tab' => $tab]) ?>
                    </li>
                <?php endforeach; ?>
        </ul>
        <div class="table-responsive">
            <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                // 'dataProvider' => $dataProvider,
                'dataProvider' => $searchModel->searchAdmin(Yii::$app->request->queryParams, $activeTab),
                'pager'        => [
                    'class'          => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel'  => 'Last'
                ],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class' => 'x'],
                'columns' => [
                    'invoice',
                    'nama',
                    'nominal',
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'usrid',
                        'value' => function ($model) {
                            if ($rel = $model->usr) {
                                return Html::a($rel->name, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                    'alamat_pembeli',
                    'alamat_penjual',
                    'berat',
                    \app\components\ActionButton::getButtons(),
                    /*'ongkir'*/
                    /*'kurir'*/
                    /*'paket'*/
                    /*'dari'*/
                    /*'tujuan'*/
                    /*'resi'*/
                    /*'id_bayar'*/
                    /*'ajukanbatal'*/
                    /*'keterangan'*/
                    /*'status_id'*/
                    /*'kirim'*/
                ],
            ]); ?>
        </div>
    </div>
</div>

<?php \yii\widgets\Pjax::end() ?>