<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\file\FileInput;

/**
* @var yii\web\View $this
* @var app\models\Produk $model
* @var yii\widgets\ActiveForm $form
*/
$this->registerJsFile(Yii::getAlias("@web/tinymce/tinymce.min.js"));
// $uploadlink = Url::to(['site/upload-image']);
// $csrf = Yii::$app->request->csrfToken;

$this->registerJs("
      tinymce.init({
        selector: '.tinymce-form',
        height: '400',
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table paste code help wordcount',
        ],

        toolbar: 'undo redo | formatselect | ' +
        'bold italic backcolor | alignleft aligncenter ' +
        'alignright alignjustify | bullist numlist outdent indent | ' +
        'removeformat | help',
      });
");
?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
        'id' => 'Produk',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
        );
        ?>
        
			<?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'harga')->textInput() ?>
			<?= $form->field($model, 'stok')->textInput() ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'kategori_produk_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\KategoriProduk::find()->all(), 'id', 'nama'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['kategori_produk_id'])),
    ]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'toko_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Toko::find()->all(), 'id', 'nama'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['toko_id'])),
    ]
); ?>
			<?= $form->field($model, 'deskripsi_singkat')->textarea(['class' => 'tinymce-form form-control']) ?> 
			<?= $form->field($model, 'deksripsi_lengkap')->textarea(['class' => 'tinymce-form form-control']) ?> 
			<?= $form->field($model, 'status_online')->dropDownList(
            ['0' => 'Tidak Aktif', '1' => 'Aktif']
    ); ?>
			<?= $form->field($model, 'foto_banner')->widget(FileInput::classname(), [
    'options' => ['accept' => 'image/*'],
]); ?>
			<?= $form->field($model, 'diskon_status')->dropDownList(
            ['0' => 'Tidak Aktif', '1' => 'Aktif']
    ); ?>
			<?= $form->field($model, 'diskon')->textInput(['type'=>'number']) ?>        <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?=  Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?=  Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>