<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Produk $model
 */

$this->title = 'Produk ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Produk', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud produk-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Produk', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
    <span class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <?= \Yii::$app->session->getFlash('deleteError') ?>
    </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('app\models\Produk'); ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    // 'id',
                    'nama',
                    'harga',
                    'stok',

                    [
                        'attribute' => 'kategori_produk_id',
                        'value' => function ($model) {
                            return $model->kategoriProduk->nama;
                        }
                    ],
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'toko_id',
                        'value' => ($model->toko ?
                            Html::a('<i class="glyphicon glyphicon-list"></i>', ['toko/index']) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->toko->nama, ['toko/view', 'id' => $model->toko->id,]) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Produk' => ['toko_id' => $model->id]])
                            :
                            '<span class="label label-warning">?</span>'),
                    ],
                    // 'deskripsi_singkat:ntext',
                    // 'deksripsi_lengkap:ntext',
                    [
                        'attribute' => 'deskripsi_singkat',
                        'format' => 'html',
                    ],
                    [
                        'attribute' => 'deksripsi_lengkap',
                        'format' => 'html',
                    ],
                    'status_online',
                    [
                        'attribute' => 'foto_banner',
                        'format' => 'html',
                        'value' => function ($model) {
                            return Html::img(\Yii::$app->request->BaseUrl . '/uploads/banner_produk/' . $model->foto_banner, ['width' => 100]);
                        },
                    ],
                    'flag',
                    'created_at',
                    'diskon_status',
                    'diskon',
                ],
            ]); ?>

            <hr />

            <?= Html::a(
                '<span class="glyphicon glyphicon-trash"></span> ' . 'Delete',
                ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                ]
            ); ?>
            <?php $this->endBlock(); ?>



            <?php $this->beginBlock('FotoProduks'); ?>
            <div style='position: relative'>
                <div style='position:absolute; right: 0px; top 0px;'>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Foto Produks',
                        ['foto-produk/index'],
                        ['class' => 'btn text-muted btn-xs']
                    ) ?>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Foto Produk',
                        ['foto-produk/create', 'FotoProduk' => ['produk_id' => $model->id]],
                        ['class' => 'btn btn-success btn-xs']
                    ); ?>
                </div>
            </div>
            <?php Pjax::begin(['id' => 'pjax-FotoProduks', 'enableReplaceState' => false, 'linkSelector' => '#pjax-FotoProduks ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?= '<div class="table-responsive">'
                . \yii\grid\GridView::widget([
                    'layout' => '{summary}{pager}<br/>{items}{pager}',
                    'dataProvider' => new \yii\data\ActiveDataProvider([
                        'query' => $model->getFotoProduks(),
                        'pagination' => [
                            'pageSize' => 20,
                            'pageParam' => 'page-fotoproduks',
                        ]
                    ]),
                    'pager'        => [
                        'class'          => yii\widgets\LinkPager::className(),
                        'firstPageLabel' => 'First',
                        'lastPageLabel'  => 'Last'
                    ],
                    'columns' => [
                        [
                            'class'      => 'yii\grid\ActionColumn',
                            'template'   => '{view} {update}',
                            'contentOptions' => ['nowrap' => 'nowrap'],
                            'urlCreator' => function ($action, $model, $key, $index) {
                                // using the column name as key, not mapping to 'id' like the standard generator
                                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                                $params[0] = 'foto-produk' . '/' . $action;
                                $params['FotoProduk'] = ['produk_id' => $model->primaryKey()[0]];
                                return $params;
                            },
                            'buttons'    => [],
                            'controller' => 'foto-produk'
                        ],
                        'id',
                        'foto',
                        'flag',
                    ]
                ])
                . '</div>' ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>

            <?php $this->beginBlock('ProdukSize'); ?>
            <div style='position: relative'>
                <div style='position:absolute; right: 0px; top 0px;'>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Produk Size',
                        ['produk-size/index'],
                        ['class' => 'btn text-muted btn-xs']
                    ) ?>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Produk Size',
                        ['produk-size/create', 'ProdukSize' => ['produk_id' => $model->id]],
                        ['class' => 'btn btn-success btn-xs']
                    ); ?>
                </div>
            </div>
            <?php Pjax::begin(['id' => 'pjax-ProdukSize', 'enableReplaceState' => false, 'linkSelector' => '#pjax-FotoProduks ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?= '<div class="table-responsive">'
                . \yii\grid\GridView::widget([
                    'layout' => '{summary}{pager}<br/>{items}{pager}',
                    'dataProvider' => new \yii\data\ActiveDataProvider([
                        'query' => $model->getProdukSize(),
                        'pagination' => [
                            'pageSize' => 20,
                            'pageParam' => 'page-produksize',
                        ]
                    ]),
                    'pager'        => [
                        'class'          => yii\widgets\LinkPager::className(),
                        'firstPageLabel' => 'First',
                        'lastPageLabel'  => 'Last'
                    ],
                    'columns' => [
                        [
                            'class'      => 'yii\grid\ActionColumn',
                            'template'   => '{view} {update}',
                            'contentOptions' => ['nowrap' => 'nowrap'],
                            'urlCreator' => function ($action, $model, $key, $index) {
                                // using the column name as key, not mapping to 'id' like the standard generator
                                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                                $params[0] = 'produk-size' . '/' . $action;
                                $params['ProdukSize'] = ['produk_id' => $model->primaryKey()[0]];
                                return $params;
                            },
                            'buttons'    => [],
                            'controller' => 'produk-size'
                        ],
                        'id',
                        'size',
                    ]
                ])
                . '</div>' ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>

            <?php $this->beginBlock('ProdukWarna'); ?>
            <div style='position: relative'>
                <div style='position:absolute; right: 0px; top 0px;'>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Produk Warna',
                        ['produk-warna/index'],
                        ['class' => 'btn text-muted btn-xs']
                    ) ?>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Produk Warna',
                        ['produk-warna/create', 'ProdukWarna' => ['produk_id' => $model->id]],
                        ['class' => 'btn btn-success btn-xs']
                    ); ?>
                </div>
            </div>
            <?php Pjax::begin(['id' => 'pjax-ProdukWarna', 'enableReplaceState' => false, 'linkSelector' => '#pjax-FotoProduks ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?= '<div class="table-responsive">'
                . \yii\grid\GridView::widget([
                    'layout' => '{summary}{pager}<br/>{items}{pager}',
                    'dataProvider' => new \yii\data\ActiveDataProvider([
                        'query' => $model->getProdukWarna(),
                        'pagination' => [
                            'pageSize' => 20,
                            'pageParam' => 'page-produkwarna',
                        ]
                    ]),
                    'pager'        => [
                        'class'          => yii\widgets\LinkPager::className(),
                        'firstPageLabel' => 'First',
                        'lastPageLabel'  => 'Last'
                    ],
                    'columns' => [
                        [
                            'class'      => 'yii\grid\ActionColumn',
                            'template'   => '{view} {update}',
                            'contentOptions' => ['nowrap' => 'nowrap'],
                            'urlCreator' => function ($action, $model, $key, $index) {
                                // using the column name as key, not mapping to 'id' like the standard generator
                                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                                $params[0] = 'produk-warna' . '/' . $action;
                                $params['ProdukWarna'] = ['produk_id' => $model->primaryKey()[0]];
                                return $params;
                            },
                            'buttons'    => [],
                            'controller' => 'produk-warna'
                        ],
                        'id',
                        'warna',
                    ]
                ])
                . '</div>' ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?php $this->beginBlock('ReviewProduks'); ?>
            <div style='position: relative'>
                <div style='position:absolute; right: 0px; top 0px;'>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Review Produks',
                        ['review-produk/index'],
                        ['class' => 'btn text-muted btn-xs']
                    ) ?>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Review Produk',
                        ['review-produk/create', 'ReviewProduk' => ['produk_id' => $model->id]],
                        ['class' => 'btn btn-success btn-xs']
                    ); ?>
                </div>
            </div>
            <?php Pjax::begin(['id' => 'pjax-ReviewProduks', 'enableReplaceState' => false, 'linkSelector' => '#pjax-ReviewProduks ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?= '<div class="table-responsive">'
                . \yii\grid\GridView::widget([
                    'layout' => '{summary}{pager}<br/>{items}{pager}',
                    'dataProvider' => new \yii\data\ActiveDataProvider([
                        'query' => $model->getReviewProduks(),
                        'pagination' => [
                            'pageSize' => 20,
                            'pageParam' => 'page-reviewproduks',
                        ]
                    ]),
                    'pager'        => [
                        'class'          => yii\widgets\LinkPager::className(),
                        'firstPageLabel' => 'First',
                        'lastPageLabel'  => 'Last'
                    ],
                    'columns' => [
                        [
                            'class'      => 'yii\grid\ActionColumn',
                            'template'   => '{view} {update}',
                            'contentOptions' => ['nowrap' => 'nowrap'],
                            'urlCreator' => function ($action, $model, $key, $index) {
                                // using the column name as key, not mapping to 'id' like the standard generator
                                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                                $params[0] = 'review-produk' . '/' . $action;
                                $params['ReviewProduk'] = ['produk_id' => $model->primaryKey()[0]];
                                return $params;
                            },
                            'buttons'    => [],
                            'controller' => 'review-produk'
                        ],
                        'id',
                        'nama',
                        'email:email',
                        'review:ntext',
                        'rating',
                        'created_at',
                    ]
                ])
                . '</div>' ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [
                        [
                            'label'   => '<b class=""># ' . $model->id . '</b>',
                            'content' => $this->blocks['app\models\Produk'],
                            'active'  => true,
                        ], [
                            'content' => $this->blocks['FotoProduks'],
                            'label'   => '<small>Foto Produks <span class="badge badge-default">' . count($model->getFotoProduks()->asArray()->all()) . '</span></small>',
                            'active'  => false,
                        ], [
                            'content' => $this->blocks['ReviewProduks'],
                            'label'   => '<small>Review Produks <span class="badge badge-default">' . count($model->getReviewProduks()->asArray()->all()) . '</span></small>',
                            'active'  => false,
                        ], [
                            'content' => $this->blocks['ProdukSize'],
                            'label'   => '<small>Produk Size <span class="badge badge-default">' . count($model->getProdukSize()->asArray()->all()) . '</span></small>',
                            'active'  => false,
                        ],
                        [
                            'content' => $this->blocks['ProdukWarna'],
                            'label'   => '<small>Produk Warna <span class="badge badge-default">' . count($model->getProdukWarna()->asArray()->all()) . '</span></small>',
                            'active'  => false,
                        ]
                    ]
                ]
            );
            ?>
        </div>
    </div>
</div>