<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Menu $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
        'id' => 'Menu',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
);
?>

<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
<?= $form->field($model, 'controller')->textInput(['maxlength' => true]) ?>
<?= $form->field($model, 'icon')->textInput(['class' => "form-control icp-auto"]) ?>
<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'parent_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Menu::find()->where(["parent_id"=>null])->orderBy("`order`")->all(), 'id', 'name'),
    ['prompt' => 'Select']
); ?>
<hr/>
<?php echo $form->errorSummary($model); ?>
<div class="row">
    <div class="col-md-offset-3 col-md-7">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

<?php
$this->registerJs('$(".icp-auto").iconpicker();');
?>