<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
?>
<hr class="mt-0">
<div class="container pb-20">
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-12 col-12">
            <?= $this->render('component/sidemenu-toko') ?>
        </div>
        <div class="col-lg-8 col-md-6 col-sm-12 col-12 profile-section">
            <h3 class="text-isalam-1 font-weight-bold text-detail-program">Produk Saya</h3>
            <div class="row pl-20 pr-20">
                <p>
                    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create-produk'], ['class' => 'btn btn-success', 'style' => 'width:140px']) ?>
                </p>


                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => "{summary}{items}<div class='d-flex justify-content-center'>{pager}</div>",
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => yii\widgets\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [

                            \app\components\ActionButton::getButtonsSaya(),

                            [
                                'attribute' => 'nama',
                                'filter' => false,
                            ],
                            [
                                'attribute' => 'harga',
                                'label' => 'Harga',
                                'format' => 'raw',
                                'filter' => false,
                                'value' => function ($model) {

                                    return \app\components\Angka::toReadableHarga($model->harga);
                                },
                            ],
                            [
                                'attribute' => 'stok',
                                'filter' => false,
                            ],
                            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                            [
                                'attribute' => 'kategori_produk_id',
                                'filter' => false,
                                'value' => function ($model) {
                                    return $model->kategoriProduk->nama;
                                }
                            ],
                            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                            // 'deskripsi_singkat:ntext',
                            // 'deksripsi_lengkap:ntext',
                            /*'status_online'*/
                            /*'flag'*/
                            /*'diskon_status'*/
                            /*'diskon'*/
                            /*'created_at'*/
                            /*'foto_banner'*/
                        ],
                    ]); ?>
                </div>

            </div>
        </div>
    </div>
</div>