<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "alamat".
 *
 * @property integer $id
 * @property integer $usrid
 * @property integer $status
 * @property integer $idkec
 * @property integer $kodepos
 * @property string $judul
 * @property string $alamat
 *
 * @property \app\models\User $usr
 * @property string $aliasModel
 */
abstract class Alamat extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'alamat';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['usrid', 'status', 'idkec', 'kodepos', 'judul', 'alamat'], 'required'],
            [['usrid', 'status', 'idkec', 'kodepos'], 'integer'],
            [['judul', 'alamat'], 'string'],
            [['usrid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['usrid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'usrid' => 'Usrid',
            'status' => 'Status',
            'idkec' => 'Idkec',
            'kodepos' => 'Kodepos',
            'judul' => 'Identitas Alamat',
            'alamat' => 'Alamat Lengkap',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsr()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'usrid']);
    }
}
