<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "detail_pesanan".
 *
 * @property integer $id
 * @property integer $invoice
 * @property string $nama
 * @property integer $nominal
 * @property string $token_midtrans
 * @property integer $usrid
 * @property string $alamat_pembeli
 * @property integer $toko_id
 * @property integer $alamat_penjual
 * @property integer $berat
 * @property integer $ongkir
 * @property string $kurir
 * @property string $paket
 * @property integer $dari
 * @property integer $tujuan
 * @property string $resi
 * @property string $kirim
 * @property integer $id_bayar
 * @property integer $ajukanbatal
 * @property string $keterangan
 * @property integer $status_id
 * @property string $selesai
 * @property string $pesanan_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Pesanan $pesanan
 * @property \app\models\User $usr
 * @property \app\models\StatusPesanan $status
 * @property string $aliasModel
 */
abstract class DetailPesanan extends \yii\db\ActiveRecord
{


    public function fields()
    {
        $parent = parent::fields();
        if (isset($parent['token_midtrans'])) {
            unset($parent['token_midtrans']);

            $parent['token_midtrans'] = function ($model) {
                return $model->token_midtrans;
            };
        }
        if (!isset($parent['url'])) {
            unset($parent['url']);

            $parent['url'] = function ($model) {
                return 'https://app.sandbox.midtrans.com/snap/v2/vtweb/' . $model->token_midtrans;
            };
        }
        unset($parent['updated_at']);
        unset($parent['created_at']);

        return $parent;
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'detail_pesanan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // [['invoice', 'nama', 'nominal', 'token_midtrans', 'usrid', 'alamat_pembeli', 'berat', 'ongkir', 'kurir', 'paket', 'dari', 'tujuan', 'id_bayar', 'ajukanbatal', 'keterangan', 'status_id'], 'required'],
            [['invoice', 'nominal', 'usrid', 'toko_id', 'alamat_penjual', 'berat', 'ongkir', 'dari', 'tujuan', 'id_bayar', 'ajukanbatal', 'status_id', 'pesanan_id'], 'integer'],
            [['kirim', 'selesai'], 'safe'],
            [['nama', 'token_midtrans', 'alamat_pembeli', 'kurir', 'paket', 'resi', 'keterangan'], 'string', 'max' => 255],
            [['pesanan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pesanan::className(), 'targetAttribute' => ['pesanan_id' => 'id']],
            [['usrid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['usrid' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StatusPesanan::className(), 'targetAttribute' => ['status_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'invoice' => 'Invoice',
            'nama' => 'Nama',
            'nominal' => 'Nominal',
            'token_midtrans' => 'Token Midtrans',
            'usrid' => 'Usrid',
            'alamat_pembeli' => 'Alamat Pembeli',
            'toko_id' => 'Toko ID',
            'alamat_penjual' => 'Alamat Penjual',
            'berat' => 'Berat',
            'ongkir' => 'Ongkir',
            'kurir' => 'Kurir',
            'paket' => 'Paket',
            'dari' => 'Dari',
            'tujuan' => 'Tujuan',
            'resi' => 'Resi',
            'kirim' => 'Kirim',
            'id_bayar' => 'Id Bayar',
            'ajukanbatal' => 'Ajukanbatal',
            'keterangan' => 'Keterangan',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status_id' => 'Status ID',
            'selesai' => 'Selesai',
            'pesanan_id' => 'Pesanan ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPesanan()
    {
        return $this->hasOne(\app\models\Pesanan::className(), ['id' => 'pesanan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsr()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'usrid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(\app\models\StatusPesanan::className(), ['id' => 'status_id']);
    }
}
