<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "foto_produk".
 *
 * @property integer $id
 * @property string $foto
 * @property integer $produk_id
 * @property integer $flag
 *
 * @property \app\models\Produk $produk
 * @property string $aliasModel
 */
abstract class FotoProduk extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public function fields()
    {
        $parent = parent::fields();
        if (isset($parent['foto'])) {
            unset($parent['foto']);
            $parent['foto'] = function ($model) {
                return Yii::getAlias("@file/foto_produk/$model->foto");
            };
        }

        return $parent;
    }
    public static function tableName()
    {
        return 'foto_produk';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['foto', 'produk_id'], 'required'],
            [['produk_id', 'flag'], 'integer'],
            [['foto'], 'string', 'max' => 255],
            [['produk_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Produk::className(), 'targetAttribute' => ['produk_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'foto' => 'Foto',
            'produk_id' => 'Produk ID',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduk()
    {
        return $this->hasOne(\app\models\Produk::className(), ['id' => 'produk_id']);
    }
}
