<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "hubungi_kami".
 *
 * @property integer $id
 * @property string $nama
 * @property string $nomor_hp
 * @property string $email
 * @property string $pesan
 * @property integer $flag
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class HubungiKami extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hubungi_kami';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'pesan'], 'required'],
            [['pesan'], 'string'],
            [['flag'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['nama', 'nomor_hp', 'email'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'nomor_hp' => 'Nomor Hp',
            'email' => 'Email',
            'pesan' => 'Pesan',
            'flag' => 'Flag',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'flag' => '0:baru,1:sudah dibaca,2:ditolak',
        ]);
    }




}
