<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "kategori_produk".
 *
 * @property integer $id
 * @property string $nama
 * @property string $icon
 * @property string $icon2
 *
 * @property \app\models\Produk[] $produks
 * @property string $aliasModel
 */
abstract class KategoriProduk extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kategori_produk';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'icon', 'icon2'], 'required'],
            [['nama', 'icon', 'icon2'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'icon' => 'Icon',
            'icon2' => 'Icon2',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduks()
    {
        return $this->hasMany(\app\models\Produk::className(), ['kategori_produk_id' => 'id']);
    }




}
