<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "member".
 *
 * @property integer $id
 * @property string $nama
 * @property string $email
 * @property integer $handphone
 * @property string $alamat
 * @property string $cabang_olahraga
 * @property string $komunitas_olahraga
 * @property integer $flag
 * @property string $aliasModel
 */
abstract class Member extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'member';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'email', 'handphone', 'alamat', 'cabang_olahraga', 'komunitas_olahraga'], 'required'],
            [['handphone', 'flag'], 'integer'],
            [['alamat', 'cabang_olahraga', 'komunitas_olahraga'], 'string'],
            [['nama', 'email'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'email' => 'Email',
            'handphone' => 'Handphone',
            'alamat' => 'Alamat',
            'cabang_olahraga' => 'Cabang Olahraga',
            'komunitas_olahraga' => 'Komunitas Olahraga',
            'flag' => 'Flag',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'flag' => '0:baru,1:diterima,2:ditolak',
        ]);
    }




}
