<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "nilai_sikap".
 *
 * @property integer $id
 * @property string $nama
 * @property string $isi
 * @property string $aliasModel
 */
abstract class NilaiSikap extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'nilai_sikap';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'isi'], 'required'],
            [['isi'], 'string'],
            [['nama'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'isi' => 'Isi',
        ];
    }




}
