<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "pembayaran".
 *
 * @property integer $id
 * @property integer $invoice
 * @property string $nama
 * @property integer $nominal
 * @property integer $usrid
 * @property integer $status_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Pembayaran extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pembayaran';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['invoice', 'nama', 'nominal', 'usrid', 'status_id'], 'required'],
            [['invoice', 'nominal', 'usrid', 'status_id'], 'integer'],
            [['nama'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'invoice' => 'Invoice',
            'nama' => 'Nama',
            'nominal' => 'Nominal',
            'usrid' => 'Usrid',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status_id' => 'Status ID',
        ];
    }




}
