<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "pesanan".
 *
 * @property string $id
 * @property integer $user_id
 * @property integer $invoice
 * @property integer $nominal
 * @property string $token_midtrans
 * @property string $ref
 * @property string $created_at
 *
 * @property \app\models\DetailPesanan[] $detailPesanans
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class Pesanan extends \yii\db\ActiveRecord
{



    public function fields()
    {
        $parent = parent::fields();
        if (isset($parent['token_midtrans'])) {
            unset($parent['token_midtrans']);

            $parent['token_midtrans'] = function ($model) {
                return $model->token_midtrans;
            };
        }
        if (!isset($parent['url'])) {
            unset($parent['url']);

            $parent['url'] = function ($model) {
                return 'https://app.sandbox.midtrans.com/snap/v2/vtweb/' . $model->token_midtrans;
            };
        }
        unset($parent['created_at']);
        return $parent;
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pesanan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'invoice', 'nominal', 'token_midtrans'], 'required'],
            [['user_id', 'invoice', 'nominal'], 'integer'],
            [['token_midtrans'], 'string', 'max' => 255],
            [['ref'], 'string', 'max' => 100],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'invoice' => 'Invoice',
            'nominal' => 'Nominal',
            'token_midtrans' => 'Token Midtrans',
            'created_at' => 'Created At',
            'ref' => 'Ref',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getdetail_pesanan()
    {
        return $this->hasMany(\app\models\DetailPesanan::className(), ['pesanan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }
}
