<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "produk".
 *
 * @property integer $id
 * @property string $nama
 * @property integer $harga
 * @property integer $stok
 * @property integer $kategori_produk_id
 * @property integer $toko_id
 * @property string $deskripsi_singkat
 * @property string $deksripsi_lengkap
 * @property integer $status_online
 * @property string $foto_banner
 * @property integer $flag
 * @property string $created_at
 * @property integer $diskon_status
 * @property integer $diskon
 *
 * @property \app\models\FotoProduk[] $fotoProduks
 * @property \app\models\KategoriProduk $kategoriProduk
 * @property \app\models\Toko $toko
 * @property \app\models\ReviewProduk[] $reviewProduks
 * @property string $aliasModel
 */
abstract class Produk extends \yii\db\ActiveRecord
{

    public function fields()
    {
        $parent = parent::fields();

        if (!isset($parent['toko'])) {
            unset($parent['toko']);
            $parent['toko'] = function ($model) {
                $toko = \app\models\Toko::findOne(['id' => $model->toko_id]);
                return $toko;
            };
        }
        // if (!isset($parent['kategori_produk'])) {
        //     unset($parent['kategori_produk']);
        //     $parent['kategori_produk'] = function ($model) {
        //         $kategori = \app\models\KategoriProduk::findOne(['id' => $model->kategori_produk_id]);
        //         return $kategori;
        //     };
        // }


        return $parent;
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'produk';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'harga', 'stok', 'kategori_produk_id', 'toko_id', 'deskripsi_singkat', 'deksripsi_lengkap'], 'required'],
            [['harga', 'stok', 'kategori_produk_id', 'toko_id', 'status_online', 'flag', 'diskon_status', 'diskon'], 'integer'],
            [['deskripsi_singkat', 'deksripsi_lengkap'], 'string'],
            [['created_at'], 'safe'],
            [['nama', 'foto_banner'], 'string', 'max' => 255],
            [['kategori_produk_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\KategoriProduk::className(), 'targetAttribute' => ['kategori_produk_id' => 'id']],
            [['toko_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Toko::className(), 'targetAttribute' => ['toko_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'harga' => 'Harga',
            'stok' => 'Stok',
            'kategori_produk_id' => 'Kategori Produk',
            'toko_id' => 'Toko',
            'deskripsi_singkat' => 'Deskripsi Singkat',
            'deksripsi_lengkap' => 'Deksripsi Lengkap',
            'status_online' => 'Status Online',
            'foto_banner' => 'Foto Banner',
            'flag' => 'Flag',
            'created_at' => 'Created At',
            'diskon_status' => 'Diskon Status',
            'diskon' => 'Diskon',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFotoProduks()
    {
        return $this->hasMany(\app\models\FotoProduk::className(), ['produk_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKategoriProduk()
    {
        return $this->hasOne(\app\models\KategoriProduk::className(), ['id' => 'kategori_produk_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getToko()
    {
        return $this->hasOne(\app\models\Toko::className(), ['id' => 'toko_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReviewProduks()
    {
        return $this->hasMany(\app\models\ReviewProduk::className(), ['produk_id' => 'id']);
    }

    public function getProductDetail()
    {
        return $this->hasMany(\app\models\ProductDetail::className(), ['id_product' => 'id']);
    }
}
