<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "product_variant".
 *
 * @property integer $id
 * @property integer $id_produk
 * @property string $type
 * @property string $value
 *
 * @property \app\models\ProductDetail[] $productDetails
 * @property \app\models\Produk $produk
 * @property string $aliasModel
 */
abstract class ProductVariant extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_variant';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_produk', 'type', 'value'], 'required'],
            [['id_produk'], 'integer'],
            [['type', 'value'], 'string', 'max' => 255],
            [['id_produk'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Produk::className(), 'targetAttribute' => ['id_produk' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_produk' => 'Id Produk',
            'type' => 'Type',
            'value' => 'Value',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductDetails()
    {
        return $this->hasMany(\app\models\ProductDetail::className(), ['id_variant' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduk()
    {
        return $this->hasOne(\app\models\Produk::className(), ['id' => 'id_produk']);
    }
}
