<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "review_produk".
 *
 * @property integer $id
 * @property integer $produk_id
 * @property string $nama
 * @property string $email
 * @property string $review
 * @property integer $rating
 * @property string $created_at
 *
 * @property \app\models\Produk $produk
 * @property string $aliasModel
 */
abstract class ReviewProduk extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'review_produk';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['produk_id', 'nama', 'email', 'review', 'rating'], 'required'],
            [['produk_id', 'rating'], 'integer'],
            [['review'], 'string'],
            [['created_at'], 'safe'],
            [['nama', 'email'], 'string', 'max' => 255],
            [['produk_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Produk::className(), 'targetAttribute' => ['produk_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'produk_id' => 'Produk ID',
            'nama' => 'Nama',
            'email' => 'Email',
            'review' => 'Review',
            'rating' => 'Rating',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduk()
    {
        return $this->hasOne(\app\models\Produk::className(), ['id' => 'produk_id']);
    }




}
