<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "toko".
 *
 * @property integer $id
 * @property string $nama
 * @property integer $id_user
 * @property string $deskripsi
 * @property string $alamat
 * @property string $latitude
 * @property string $longitude
 * @property string $no_whatsapp
 * @property integer $flag
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Produk[] $produks
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class Toko extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'toko';
    }

    /**
     * @inheritdoc
     */

    public function rules()
    {
        return [
            [['nama', 'id_user', 'deskripsi', 'idkec', 'kodepos', 'alamat', 'no_whatsapp'], 'required'],
            [['id_user', 'flag', 'idkec', 'kodepos'], 'integer'],
            [['deskripsi', 'alamat'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['nama', 'latitude', 'longitude'], 'string', 'max' => 255],
            [['no_whatsapp'], 'string', 'max' => 18],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['id_user' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'id_user' => 'Id User',
            'deskripsi' => 'Deskripsi',
            'idkec' => 'Distrik',
            'kodepos' => 'Kode Pos',
            'alamat' => 'Alamat',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'no_whatsapp' => 'No Whatsapp',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduks()
    {
        return $this->hasMany(\app\models\Produk::className(), ['toko_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'id_user']);
    }
}
